version: "3.8"

services:
  snake-app:
    build: .
    container_name: snake_app
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data: